### ISSUE TITLE
Operations other than getting info?

### ISSUE THREAD

**Issue by driftingaway86** [stefano-pogliani/jmx-rust#1]
Do you plan to add other operations such as exec and run on mbean operations?

**Comment by stefano-pogliani** [comment]
Hello :wave: 
Sorry for getting back to you only now.

No, I do not plan to make this a fully featured JMX implementation any time soon.

From what little I've seen of JMX while building this crate I'd suggest you do anything more complex then getting info in Java itself.
If you need to keep the Java code to a minimum maybe you could build a thin Java adaptor API to interact with JMX and then use a different, rust-native, protocol to interact with that adaptor?
